# run: conda env create --file requirements.yml
name: agemo_dev
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - numpy>=1.17
  - numba>=0.54.0
  - pytest>=6.2.5
  - sage>=9.2
  - maxima>=5.45.0